version: '2'

services:
  app:
    container_name: app
    build: apps/app
    networks:
      - local-network
    environment:
      - NODE_ENV=production
      - PORT=5000

  sidebar:
    container_name: sidebar
    build: apps/sidebar
    networks:
      - local-network
    environment:
      - NODE_ENV=production
      - PORT=5000

  dashboard:
    container_name: dashboard
    build: apps/dashboard
    networks:
      - local-network
    ports:
      - "80:80"

  portfolio:
    container_name: portfolio
    build: apps/portfolio
    networks:
      - local-network
    environment:
      - NODE_ENV=production
      - PORT=5000

  nginx:
    container_name: nginx
    build: nginx
    ports:
      - "8888:80"
    networks:
      - local-network
    depends_on:
      - sidebar
      - dashboard
      - portfolio

networks:
  local-network:
